=== davydovpv/SOA_Stock/xmlFiles/API1.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="QuoteData">
<xs:complexType>
  <xs:sequence>
  	<xs:element name="StockSymbol" type="xs:string"/>
  	<xs:element name="LastTradeAmount" type="xs:string"/>
  	<xs:element name="StockChange" type="xs:string"/>
  	<xs:element name="OpenAmount" type="xs:string"/>
  	<xs:element name="DayHigh" type="xs:string"/>
  	<xs:element name="DayLow" type="xs:string"/>
  	<xs:element name="PrevCls" type="xs:string"/>
  	<xs:element name="ChangePercent" type="xs:string"/>
  	<xs:element name="FiftyTwoWeekRange" type="xs:string"/>
  	<xs:element name="EarnPerShare" type="xs:string"/>
  	<xs:element name="PE" type="xs:string"/>
  	<xs:element name="CompanyName" type="xs:string"/>
  	<xs:element name="QuoteError" type="xs:string"/>
  </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>

=== davydovpv/SOA_Stock/xmlFiles/API1.xml
<QuoteData xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="API1.xsd" xmlns="http://ws.cdyne.com/">
<StockSymbol>SINA</StockSymbol>
<LastTradeAmount>49.99</LastTradeAmount>
<LastTradeDateTime>2016-04-15T16:00:00</LastTradeDateTime>
<StockChange>-0.09</StockChange>
<OpenAmount>50.20</OpenAmount>
<DayHigh>50.20</DayHigh>
<DayLow>49.76</DayLow>
<StockVolume>511785</StockVolume>
<PrevCls>50.08</PrevCls>
<ChangePercent>-0.18%</ChangePercent>
<FiftyTwoWeekRange>32.61 - 61.25</FiftyTwoWeekRange>
<EarnPerShare>1.19</EarnPerShare>
<PE>42.08</PE>
<CompanyName>Sina Corporation</CompanyName>
<QuoteError>false</QuoteError>
</QuoteData>
