=== davydovpv/SOA_Stock/xmlFiles/API2.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:element name="stocks">
<xs:complexType>
  <xs:sequence>
  	<xs:element name="stock">
      <xs:complexType>
        <xs:sequence>
  	      <xs:element name="symbol" type="xs:string"/>
        	<xs:element name="ask" type="xs:string"/>
        	<xs:element name="bid" type="xs:string"/>
        	<xs:element name="last-trade-date" type="xs:string"/>
        	<xs:element name="low" type="xs:string"/>
        	<xs:element name="high" type="xs:string"/>
        	<xs:element name="low-52-weeks" type="xs:string"/>
        	<xs:element name="high-52-weeks" type="xs:string"/>
        	<xs:element name="EarnPerShare" type="xs:string"/>
        	<xs:element name="volume" type="xs:string"/>
        	<xs:element name="open" type="xs:string"/>
        	<xs:element name="close" type="xs:string"/>
        </xs:sequence>
       </xs:complexType>
    </xs:element>
  </xs:sequence>
 </xs:complexType>
</xs:element>
</xs:schema>

=== davydovpv/SOA_Stock/xmlFiles/API2.xml
<stocks xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="API2.xsd" xmlns="http://ws.cdyne.com/">
<stock>
<symbol>SINA</symbol>
<ask>50.15</ask>
<bid>45.74</bid>
<last-trade-date>4/15/2016</last-trade-date>
<low>49.76</low>
<high>50.20</high>
<low-52-weeks>32.61</low-52-weeks>
<high-52-weeks>61.25</high-52-weeks>
<volume>511785</volume>
<open>50.20</open>
<close>49.99</close>
</stock>
</stocks>
